   version: '3'
   services:
     bot-gpt:
       build:
         context: .
         dockerfile: Dockerfile
       environment:
         - DISCORD_TOKEN=${DISCORD_TOKEN}
         - OPENAI_API_KEY=${OPENAI_API_KEY}
         - PPLX_API_KEY=${PPLX_API_KEY}
